config/routes.rb
MoneyApp::Application.routes.draw do

  resources :bills

  devise_for :users

	root :to => 'static_pages#home'
	
	get "about" => "static_pages#about"

  

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :cost, :description, :name
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :bills
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

before_filter :authenticate_user!, except: [:index]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = current_user.bills.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = current_user.bills.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = current_user.bills.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
   @bill = current_user.bills.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = current_user.bills.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if user_signed_in?
      redirect_to bills_path
  	end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <tr>
    <th>Cost</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bills.each do |bill| %>
  <tr>
    <td>&pound;<%= bill.cost %></td>
    <td><%= bill.name %></td>
    <td><%= bill.description %></td>
    <td><%= link_to 'Show', bill %></td>
    <% if current_user == bill.user %>
    <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
    <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cost:</b>
  <%= @bill.cost %>
</p>

<p>
  <b>Name:</b>
  <%= @bill.name %>
</p>

<p>
  <b>Description:</b>
  <%= @bill.description %>
</p>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoneyApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-narrow">
    
     <div class="masthead">
        <ul class="nav nav-pills pull-right">
           <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
           <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
           <% end %>
        </ul>
        <h3 class="muted">Monies</h3>
     </div>

			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
		
		<%= yield %>
		

      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>
	
    </div> <!-- /container -->	
	
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About monies App</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

<p>this is farleys change</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
	<% if user_signed_in? %>
		<p>Hello <%= current_user.email %> </p>
	<% else %>
	 	<h1>Welcome to Monies</h1>
        	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-large btn-success" %> 
	<% end %>
</div>

<div class="row-fluid marketing">

<% if user_signed_in? %>

	<% else %>
	
<div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
 </div>

 <div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
 </div>
 
	<% end %>

</div>

      <hr>